[package]
name = "kernsec"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
clap = { version = "3.2.17", features = ["derive"] }
flate2 = "1.0.24"
sysctl = "0.5.2"
efivar = "0.2.1"
